# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d7976201ae49f21df47691ca7dcad9f4a58fc70857b5b130f7b9a432e075d3f54645831084d611b36b610bcbae8c3e3c22bce45b6f55d00475e6760a9547b24

test:
  secret_key_base: 8eb7464784e7924b2100fd0552c2f585b542e957605504ff93fa487e7c5119aca9f6f79260ca8a5800a49fa64c328c110097ca6d31e1387dde0fa6a165f96ef2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
